/******************************************************************************
 * pos_uart.h
 *
 *  Created on: 31/Aug/2015
 *      Author: Rogerio
 *****************************************************************************/
#ifndef PSO_DATA_H_
#define PSO_DATA_H_


//typedef struct __pso_raw_data_t
//{
// uint32_t edge_count_rpm; /*< Propeller rotation (rpm)*/
// int16_t adc_v_motor; /*< Motor voltage (V)*/
// int16_t adc_i_motor; /*< Motor current (A)*/
// int16_t adc_thrust; /*< Thrust generated by the propulsion system (N)*/
// int16_t adc_accel[3]; /*< Accelerometer readings (raw)*/
// uint8_t rpm_new_data;
// uint8_t adc_new_data;
//} pso_raw_data_t;


/******************************************************************************
*
*  The following are prototypes for the UART functions.
*
******************************************************************************/
uint8_t copy_raw_data (uint8_t* txBuffer, uart_raw_data_t* g_uart0_data);
uint8_t read_raw_data (uart_raw_data_t* g_uart0_data);

#endif /* PSO_DATA_H_ */
